# Docker Compose para levantar backend, frontend y tests.
# Notas importantes:
# - Protegemos node_modules en los contenedores con volúmenes específicos
#   para evitar sobrescrituras desde macOS (darwin) -> linux mismatch.
# - El servicio "tests" no monta ./tests para no sobreescribir node_modules
#   instalados durante el build (evita MODULE_NOT_FOUND).
version: '3.9'

services:
  backend:
    build: ./backend
    container_name: microapp-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app:delegated
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: microapp-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    command: npm run dev

  tests:
    build: ./tests
    container_name: microapp-tests
    depends_on:
      - backend
      - frontend
    # Ejecutamos tests dentro del contenedor (no montamos /app para no sobreescribir node_modules)
    command: npx playwright test --reporter=list
    environment:
      - BASE_URL=http://frontend:3000
    # No montar ./tests en /app para preservar instalaciones hechas en build
    # Si necesitas editar tests desde host, quítalo (pero entonces re-instala deps en runtime).
    tty: true

volumes:
  backend_node_modules:
  frontend_node_modules:
