version: '3.9'

services:
  backend:
    build: ./backend
    container_name: microapp-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app:delegated
      - backend_node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: microapp-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:4000
    volumes:
      - ./frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    command: npm run dev

  tests:
    build: ./tests
    container_name: microapp-tests
    depends_on:
      - backend
      - frontend
    environment:
      BASE_URL: http://localhost:3000
      DISPLAY: :99
    ports:
      - "5900:5900"   # VNC
      - "8080:8080"   # noVNC
    volumes:
      - ./tests:/app:delegated
      - tests_node_modules:/app/node_modules
    tty: true
    entrypoint: ["/bin/bash", "/app/entrypoint.sh"]  # modo normal
    # entrypoint: ["/bin/bash", "/app/entrypointDemo.sh"] # modo demo

volumes:
  backend_node_modules:
  frontend_node_modules:
  tests_node_modules:
